---
plugin: aws_ec2
aws_access_key: my access key
aws_secret_key: my secret key

regions:
  - us-east-1

# keyed_groups may be used to create custom groups
keyed_groups:
  # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags
  # Create a group for each value of the Group tag. Ex: "Key=Group Value=Production"
  - key: tags.Group
    separator: ''
  # Adds hosts based on instance_type, e.g. t2.micro
  - key: instance_type
    prefix: instance_type
  # Create a group per region e.g. aws_region_us_east-1
  - key: placement.region
    prefix: aws_region

# Add all instances with their "Group" tag set to "Production"
# Return specific hosts only: Name/Value tag pair. Add multiple hosts "- tag:Name=Tag1,Name=Tag2"
filters:
  tag:Group:
    - Production
  tag:Name:
    - Prod-AMZLinux2-1 
    
